Repository histovec/histovec-beta, pull requests merged in 2023-03, with the labels that each got.

#1422 RGAA-1.2 enlever alt sur image presentation de l'onglet ErreurPage
  frontend/src/views/error/ErrorPage.vue
Labels: Ready to review

#1404 fix(RGAA-11.9-12.8-7.4): Bouton Effacer réinitialise les champs du formulaire
  frontend/src/views/ProprietairePage.vue
Labels: Ready to review

#1402 fix(RGAA-7.1): Rendre les items "Où les trouver" du formulaire navigable et sélectionnable au clavier
  frontend/src/views/ProprietairePage.vue
Labels: Ready to review

#1409 fix(RGAA-8.2): validator sur ContactPage
  frontend/src/views/ContactPage.vue
Labels: Ready to review

#1395 fix(RGAA-9.1-10.7): Refonte du footer
  frontend/src/components/HistoVecFooter.vue
Labels: Rework needed

#1412 fix(RGAA-8.2): validator w3c sur ProprietairePage
  frontend/src/views/ProprietairePage.vue
Labels: Ready to review

#1386 fix(RGAA-6.1): supprimer redondance simplimmat
  frontend/src/views/RapportPage.vue
Labels: Ready to review

#1400 fix(RGAA-11.11): message erreur mail
  frontend/src/views/ContactPage.vue
Labels: Waiting

#1398 fix(RGAA-7.4): remonter en haute de page apres une redirection
  frontend/src/components/HistoVecHeader.vue
  frontend/src/router/index.js
Labels: Ready to review

#1420 creer fichier css global
  frontend/src/assets/stylesheets/globale.css
  frontend/src/assets/stylesheets/image.css
  frontend/src/components/ImagePresentation.vue
  frontend/src/views/AccessibilitePage.vue
  frontend/src/views/ContactPage.vue
  frontend/src/views/DonneesPersonnellesEtCookiesPage.vue
  frontend/src/views/MentionsLegalesPage.vue
  frontend/src/views/PlanDuSitePage.vue
  frontend/src/views/ProprietairePage.vue
  frontend/src/views/RapportPage.vue
Labels: Ready to review

#1419 refacto des constantes du csaPdf
  frontend/src/constants/csaAsPdf.js
  frontend/src/utils/csaAsPdf/content.js
  frontend/src/utils/csaAsPdf/footer.js
  frontend/src/utils/csaAsPdf/index.js
  frontend/src/utils/csaAsPdf/utils.js
  frontend/src/views/RapportPage.vue
Labels: Ready to review

#1434 fix(RGAA-1.2): retirer alt sur image presentation page Acheteur
  frontend/src/views/AcheteurPage.vue
Labels: Ready to review

#1436 fix(RGAA-10.5): ajouter background dans les accordéons de mentions légales
  frontend/src/views/MentionsLegalesPage.vue
Labels: Ready to review

#1437 fix: correction de l'envoie des lettres accentuees dans les mails
  frontend/src/views/ContactPage.vue
Labels: Ready to review

#1359 feat(); initialisation des tests unitaires
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CarteDsfrNonCliquable.vue
  frontend/src/components/HistoVecButtonLink.vue
  frontend/src/components/ImagePresentation.vue
  frontend/src/tests/unit/components/AlerteComponent.spec.js
  frontend/src/tests/unit/components/CarteDsfrNonCliquable.spec.js
  frontend/src/tests/unit/components/HistoVecButtonLink.spec.js
  frontend/src/tests/unit/components/HistoVecFooter.spec.js
  frontend/src/tests/unit/components/HistoVecModale.spec.js
  frontend/src/tests/unit/components/ImagePresentation.spec.js
  frontend/src/tests/unit/components/LoaderComponent.spec.js
  frontend/src/tests/unit/components/TuileDsfrNonCliquable.spec.js
  frontend/src/tests/unit/utils/format.spec.js
  frontend/src/tests/unit/views/AccueilPage.spec.js
  frontend/src/views/AccueilPage.vue
  frontend/vitest.config.ts
Labels: Ready to review

#1363 feat(); initialisation des tests unitaires
  .gitignore
  frontend/cypress.config.js
  frontend/cypress/constants/urls.json
  frontend/cypress/e2e/accueil/accueil.cy.js
  frontend/cypress/e2e/acheteur/acheteur.cy.js
  frontend/cypress/e2e/contact/pageContact.cy.js
  frontend/cypress/e2e/faq/selectFaqPage.cy.js
  frontend/cypress/e2e/proprietaire/rechercherImmatDepuis2009.cy.js
  frontend/cypress/e2e/rapport/modalePartageRapport/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletControlesTechniques/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletHistorique/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletKilometrage/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletSituationAdministrative/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletSynthese/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletTitulaireEtTitre/casSimple.cy.js
  frontend/cypress/e2e/rapport/ongletVehicule/casSimple.cy.js
  frontend/cypress/e2e/rapport/tuiles/casSimple.cy.js
  frontend/cypress/fixtures/aucuneAnomalie.json
  frontend/cypress/fixtures/example.json
  frontend/cypress/fixtures/perteCertificatImatriculation.json
  frontend/cypress/plugins/index.js
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/ContactPage.vue
  frontend/src/views/ProprietairePage.vue
  frontend/src/views/RapportPage.vue
Labels: Ready to review

#1415 reduire log en production
  backend/src/plugins/public-api/handlers/report.js
  backend/src/plugins/public-api/routes/reportCommon.js
  backend/src/routes/report.js
  backend/src/services/siv.js
Labels: Ready to review

#1362 Anonymiser les données personnelles qui s'affichent dans les logs
  backend/src/plugins/public-api/handlers/report.js
  backend/src/plugins/public-api/routes/reportCommon.js
  backend/src/services/utac.js
  backend/src/util/anonymiserData.js
Labels: Ready to review
